## Database Properties
spring:
  datasource:
    url: 'jdbc:h2:file:./demo'
    driverClassName: org.h2.Driver
    username: admin
    password: admin123!
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create # Hibernate ddl auto (create, create-drop, validate, update)
  h2:
    console:
      enabled: true
  application:
    name: Beginner project
server:
  port: 8080 #app port